### ISSUE TITLE
cmake with error!!

### ISSUE THREAD

**Issue by silenceday** [xiaoshichang/scarlett#1]
BuildType: 
XG_LIBRARY found: 
ASSIMP_LIBRARY found: ASSIMP_LIBRARY-NOTFOUND
IRRXML_LIBRARY found: IRRXML_LIBRARY-NOTFOUND
ZLIB_LIBRARY found: ZLIB_LIBRARY-NOTFOUND
Test_GL_Complie_Flag: /EHsc
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ASSIMP_LIBRARY
    linked by target "Scarlett" in directory C:/Users/maruofei/Downloads/scarlett-master/Engine
    linked by target "Test_Assimp" in directory C:/Users/maruofei/Downloads/scarlett-master/Tests
IRRXML_LIBRARY
    linked by target "Scarlett" in directory C:/Users/maruofei/Downloads/scarlett-master/Engine
    linked by target "Test_Assimp" in directory C:/Users/maruofei/Downloads/scarlett-master/Tests
ZLIB_LIBRARY
    linked by target "Scarlett" in directory C:/Users/maruofei/Downloads/scarlett-master/Engine
    linked by target "Test_Assimp" in directory C:/Users/maruofei/Downloads/scarlett-master/Tests

**Comment by xiaoshichang** [comment]
this demo engine depend on some other library and i put them all in external directory. in a word, you need to do this:
1. cd scarlett
2. git submodule init
3. git submodule update
4. use vs2017 to open scarlett directory. make sure your vs support cmake project.
5. build it
